// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgkhmvbcxzntttdvswmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impna2htdmJjeHpudHR0ZHZzd212Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzAxODQsImV4cCI6MjA3NDY0NjE4NH0.4vFnlf2In7Q_r2rvaZ9cuMmQgY8XFs00kuAlM6v8WDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});